### ISSUE TITLE
Org policy need to set 

### ISSUE THREAD

**Issue by yinghli** [GoogleCloudPlatform/solutions-floating-ip-patterns-terraform#101]
constraints/compute.requireShieldedVm (Enforcement: Off)
constraints/storage.uniformBucketLevelAccess (Enforcement: Off)
constraints/cloudfunctions.allowedIngressSettings (Policy values: Allow ALL)

**Comment by eeaton** [comment]
These org policies are set on some internal employee test environments but are not necessarily representative of environments where customers deploy this code.

It is recommended to loosen the org policies in your internal test environment, rather than accommodate some optional org policies in this workload-level terraform script that will consumed by people without the same org policy restrictions.

I've adjusted the Storage Bucket UBLA settings to reduce friction (it's a clear security best practice anyway) but the other 2 policies I won't fix.
